name: 'Example: Translatable Configuration'
type: module
description: 'Demonstrates how to create a custom translatable config form.'
package: Example modules
core_version_requirement: '^10.6 || ^11.0'
dependencies:
  - drupal:config_translation
  - examples:examples

# Information added by Drupal.org packaging script on 2026-04-08
version: '4.0.5'
project: 'examples'
datestamp: 1775665285
