<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types = 1);

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_templates_library_info_build(): array {
  return ckeditor5_plugin_pack_library_loader(['template']);
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_templates_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

/**
 * Implements hook_uninstall().
 */
function ckeditor5_plugin_pack_templates_uninstall($is_syncing): void {
  if (!$is_syncing) {
    ckeditor5_plugin_pack_remove_ckeditor_plugins(['insertTemplate']);
  }
}

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_plugin_pack_templates_library_info_alter(&$libraries, $extension): void {
  if ($extension === 'core' && isset($libraries['ckeditor5'])) {
    if (version_compare($libraries['ckeditor5']['version'], '44.0.0') >= 0) {
      $libraries['ckeditor5']['dependencies'][] = 'ckeditor5_plugin_pack_templates/distribution-channel';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ckeditor5_plugin_pack_templates_form_filter_format_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  $form['#validate'][] = 'ckeditor5_plugin_pack_templates_filter_format_form_validate';
}

/**
 * Validation callback for the filter format form.
 */
function ckeditor5_plugin_pack_templates_filter_format_form_validate($form, \Drupal\Core\Form\FormStateInterface $form_state): void {
  $editor = $form_state->getValue(['editor', 'editor']);
  if ($editor !== 'ckeditor5') {
    return;
  }

  $toolbar_items = $form_state->getValue(['editor', 'settings', 'toolbar', 'items']);
  if (!$toolbar_items) {
    return;
  }

  if (is_string($toolbar_items)) {
    $toolbar_items = json_decode($toolbar_items, TRUE);
  }

  // Check if "Content templates" plugin is active.
  if (is_array($toolbar_items) && in_array('insertTemplate', $toolbar_items)) {
    /** @var \Drupal\ckeditor5_plugin_pack\Config\SettingsConfigHandlerInterface $config_handler */
    $config_handler = \Drupal::service('ckeditor5_plugin_pack.config_handler.settings');
    if ($config_handler->isCdnBlocked() && !$config_handler->libraryExists('template')) {
      $form_state->setErrorByName('editor][settings][toolbar][items', t('The "Content templates" CKEditor 5 plugin requires the "template" library to be present locally. Please check your <a href=":config_url">configuration</a>. Enabling the "Block CDN source" option without providing a local path for libraries may make the required template.js file unavailable in the system.', [
        ':config_url' => \Drupal::urlGenerator()->generateFromRoute('ckeditor5_plugin_pack.settings'),
      ]));
    }
  }
}
